version: '3.9'

services:
  
  # Node API Service
  api:
    build: .
    ports:
      - 8081:8081
    container_name: sepbeats_api
    environment:
      NODE_ENV: production
      PORT: 8081
      SHOPIFY_CLI_PARTNERS_TOKEN: atkn_6c4579a90cc07d9972231316a6c0b0633ff3c69d8c26c165638478f22a2d75d3
      SHOPIFY_API_KEY: 9859d732ad91878e99dad45eb014f0cb
      SHOPIFY_API_SECRET: 76fca78e396389cd02e02cc544175aa4
      SCOPES: read_products,write_products,write_themes,read_themes,write_script_tags,read_publications,write_publications
      # HOST: https://bbbe-103-129-208-32.in.ngrok.io
    networks:
      - sepbeats_network

networks:
  sepbeats_network:
    driver: bridge